version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:80"
    networks:
      - laravel
    depends_on:
      - db
      - mailhog
      - redis
    environment:
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025

  db:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: desafio_tray
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
    redis_data:
