version: '3.8'

services:
#   app:
#     build: .
#     ports:
#       - "8000:80"
#     networks:
#       - app-network
#     depends_on:
#       - database

  database:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
